spring:
  application:
    name: mang-joo-api
  data:
    redis:
      host: localhost
      port: 6379
  session:
    redis:
      namespace: spring:session
      flush-mode: on-save
      repository-type: default
    timeout: 30m
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
